<?php
// $Id$


function kids_images_perm() 
{
	return array('list kids_images');
}


function kids_images_menu() 
{
	$items = array();
	$items['admin/build/kids_images'] = array(
		'title' => 'Manage Kids Images',
		'description' => t('Configure Images'),
		'page callback' => 'kids_images_admin_display',
		'access arguments' => array('administer kids_images'),
		'file' => 'kids_images.admin.inc',
	);
	$items['admin/build/kids_images/list'] = array(
		'title' => 'List',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -10,
	);
	$items['admin/build/kids_images/%kids_images/configure'] = array(
    	'title' => 'Configure Files Paths',
    	'page callback' => 'drupal_get_form',
    	'page arguments' => array('kids_images_admin_configure', 3),
    	'access arguments' => array('administer kids_images'),
    	'type' => MENU_CALLBACK,
    	'file' => 'kids_images.admin.inc',
  	);
	return $items;
}

/*
	Get ALL's
*/
function kids_images_load($array = array()) 
{
  
  $query = array();
  $params = array();

  if (is_numeric($array)) {
    $array = array('kid' => $array);
  }
  elseif (!is_array($array)) {
    return FALSE;
  }

  foreach ($array as $key => $value) {
    if ($key == 'kid' ) {
      $query[] = "$key = %d";
      $params[] = $value;
    }
    else {
      $query[]= "LOWER($key) = LOWER('%s')";
      $params[] = $value;
    }
  }
  $kid= db_fetch_object(db_query('SELECT * FROM {kids_images} WHERE '. implode(' AND ', $query), $params));
  return $kid;
}




