<?php
// $Id$


function credits_block($op='list', $delta=1, $edit=array()) 
{
	switch ($op) {
				case 'list':
						$blocks[0]['info'] = t('Credits on Bottom of Page');
						return $blocks;
				case 'view':
						$blocks['content'] = credits_html();
						return $blocks;
	}
}

function credits_html()
{
		global $base_url;
		$tPath = $base_url.'/sites/all/themes/advancesSpex/images/';
		

		$out = '';
		
		$out .= '<table width="100%" border="0" cellspacing="0" cellpadding="0">';
		$out .= '<tr>';
		$out .= '<td width="31" align="left" valign="top">&nbsp;</td>';
		$out .= '<td width="782" align="left" valign="top" class="tahoma-11">Copyrights &copy; 2009. Advancespex. All Rights Reserved. // '.l('Privacy Policy', 'node/31').' // '.l('Terms of Use', 'node/30').'</td>';
		$out .= '<td width="150" align="left" valign="top" class="tahoma-11">Site Credit: <strong><a href="http://www.medialinkers.com">Medialinkers</a></strong></td>';
		$out .= '</tr>';
		$out .= '</table>';
		
		return $out;
}
